#!/bin/bash

PREFIX="/site/gbif/lsp"

cd /site/gbif/dwc

echo "spise lav..."
cat /site/gbif/tmp/Lav_BG/DC_UTF_1.TXT /site/gbif/tmp/Lav_BG/DC_UTF_2.TXT | ./bin/dwclean -e -v -fnodwc -iBG -cL 2>$PREFIX/fb1ecd28-f09e-4747-8bde-0b3d7a6f78d1/errors.txt >$PREFIX/fb1ecd28-f09e-4747-8bde-0b3d7a6f78d1/dwc.txt
echo "ooook"

pushd $PREFIX/fb1ecd28-f09e-4747-8bde-0b3d7a6f78d1
echo "$(wc -l dwc.txt) records and $(grep -v info errors.txt | wc -l) errors"

../import
../lspstats

rm -f lock

echo "ライブ..."

