#!/bin/bash

cd /Users/bie/dwc

echo "spise spise..."
./bin/dwclean -iGBIF -r -cImport -vrmbu -fgbif -xverbatim.txt 2>errors.txt >dwc.txt

echo "rydde i gamle filer..."
rm -f ~/tmp/gbif/data/*.db
rm -f ~/tmp/gbif/data/*idx*

mv dwc.txt verbatim.txt errors.txt ~/tmp/gbif/import/
cd ~/tmp/gbif/import

echo "dytte ting i database..."
./import.pl dwc.txt
./import-v.pl verbatim.txt
./import-e.pl errors.txt

echo "tegne kart..."
perl kart.pl dwc.txt
/usr/local/bin/lua kart-count.lua
mv kart-count.db kart.db

mv *.db ../data/
cd ../data/

echo "oppslagsverk..."
/usr/local/bin/lua coordinateSystem.lua | sort -u > coordinatesystems.txt
/usr/local/bin/lua countries.lua | sort -u > countries.txt
/usr/local/bin/lua county.lua | sort -u > kommuner.txt
/usr/local/bin/lua stateProvince.lua | sort -u > fylker.txt
/usr/local/bin/lua search.lua
./index

rm -f ~/datasets/gbif/data/*.db
rm -f ~/datasets/gbif/data/*.idx.*

echo "ライブ..."
cp -R *.db *.idx.* *.txt ~/datasets/gbif/data/

