#!/bin/bash

cd /Users/bie/dwc

echo "spise spise..."
./bin/dwclean -v -i "NTNU-VM" -c "Oikos_2008-2013" -xverbatim.txt -fdwc -bHumanObservation < tmp/oikos2.csv 2>errors.txt >dwc.txt

echo "rydde i gamle filer..."
rm -f ~/tmp/oikos/data/*.db
rm -f ~/tmp/oikos/data/*idx*

mv dwc.txt verbatim.txt errors.txt ~/tmp/oikos/import/
cd ~/tmp/oikos/import

echo "dytte ting i database..."
lspimport dwc.txt
lspimportv verbatim.txt
lspimporte errors.txt

echo "tegne kart..."
perl kart.pl dwc.txt
/usr/local/bin/lua kart-count.lua
mv kart-count.db kart.db

mv *.db ../data/
cd ../data/

echo "oppslagsverk..."
/usr/local/bin/lua coordinateSystem.lua | sort -u > coordinatesystems.txt
/usr/local/bin/lua countries.lua | sort -u > countries.txt
/usr/local/bin/lua county.lua | sort -u > kommuner.txt
/usr/local/bin/lua stateProvince.lua | sort -u > fylker.txt
/usr/local/bin/lua search.lua
./index

rm -f ~/datasets/oikos/data/*.db
rm -f ~/datasets/oikos/data/*.idx.*

echo "ライブ..."
cp -R *.db *.idx.* *.txt ~/datasets/oikos/data/

